name: 01-Feature
on:
  push:
    branches:
      - feature/*

permissions:
  pull-requests: write

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions-tools/yaml-outputs@v2
        id: config
        with:
          file-path: 'config-pipeline.yml'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ steps.config.outputs.unit-tests__directory }}/requirements.txt

      - name: Run tests and collect coverage
        run: |
          coverage run -m pytest --source app
          coverage report --fail-under=${{ steps.config.outputs.unit-tests__fail-under }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./app/Dockerfile
          push: false

  create-pr:
    name: Create Pull Request
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
              
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "$(gh pr list --base develop --head ${{ github.ref_name }} --json number --jq '.[0].number')"]; then
            gh pr create --base develop --head ${{ github.ref_name }} --title "Automated PR from ${{ github.ref_name }} to develop" --body "This PR was created automatically by the GitHub Actions workflow."
          else
            echo "Pull request already exists."
          fi