name: 01-Develop
on:
  push:
    branches:
      - develop

permissions:
  pull-requests: write
  id-token: write
  contents: write

jobs:
  ecs-deployment:
    uses: ./.github/workflows/ecs-deployment.yml
    with:
      environment: dev
      create_release: true