name: Deploy to Production

on:
  pull_request:
    types: [labeled, unlabeled, opened, synchronize]
    branches:
      - 'release/**'    
    

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check for 'ready-to-deploy' label
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'ready-to-deploy') }}
        run: |
          echo "Error: The pull request does not have the 'ready-to-deploy' label."
          exit 1

      - name: Deploy to Production
        run: |
          echo "Deploying to production..."
          # Add your deployment commands here