name: Build Docker Image
on:
  push:
    branches:
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./app
          file: ./app/Dockerfile
          push: false

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: feature/${{ github.head_ref }}
          base: develop
          title: 'Automated PR from feature branch'
          body: 'This PR was created automatically by the GitHub Actions workflow.'          